language: node_js

node_js:
  - 'stable'
  - '8'
  - '7'
  - '6'

sudo: false

branches:
  only:
  - master

install:
  - npm uninstall typescript --no-save
  - npm install

cache:
  directories:
    - node_modules
