language: node_js

node_js:
  - '12'
  - '10'
  - '11'

script:
 - npm test
 - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

sudo: false

branches:
  only:
  - master

install:
  - npm uninstall typescript --no-save
  - npm install

cache:
  directories:
    - node_modules
